Credits-Page
coreboot-builder/coreboot-builder pull request #42
Opened 2016-12-27 13:34 UTC by juliandortmund

2016-12-27 15:14 UTC, sphinxc0re commented
How about adding the Github handle as well? @zaolin @debao84 @schutzle

2016-12-27 15:15 UTC, sphinxc0re commented
Also, could you add a screenshot of the current status?

2016-12-27 15:56 UTC, juliandortmund commented
Sure. Github handels are added. Current status
<img width="1317" alt="screen shot 2016-12-27 at 16 54 10" src="https://cloud.githubusercontent.com/assets/1820777/21503143/54cfb92c-cc55-11e6-8667-1e00c18ca1a7.png">

2016-12-27 16:19 UTC, sphinxc0re requested changes

2016-12-27 16:19 UTC, sphinxc0re commented on app/views/frontend/credits.html.haml
> +          .card.blue-grey.darken-1
grey.darken-2 or 1 would be better

2016-12-27 16:28 UTC, juliandortmund commented
Like that: 
<img width="769" alt="screen shot 2016-12-27 at 17 27 32" src="https://cloud.githubusercontent.com/assets/1820777/21503743/d8a8d2ac-cc59-11e6-9dc8-41cadc17701e.png">

2016-12-27 16:45 UTC, sphinxc0re approved these changes

2016-12-28 17:56 UTC, juliandortmund commented
@sphinxc0re @zaolin can I merge this branch into `master`?

2016-12-28 18:08 UTC, merged

2016-12-28 18:20 UTC, sphinxc0re commented
Done :grin: good job!